spring:
  application:
    name: myblog
  datasource:
    url: jdbc:postgresql://localhost:5432/myblog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  error:
    include-stacktrace: never

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE